# Generated by Django 4.1.2 on 2022-10-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workers',
            new_name='Worker',
        ),
    ]
