# Generated by Django 4.1.2 on 2022-10-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_workers_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
